name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

            - name: Setup Cpp (C++ / C)
  # You may pin to the exact commit or the version.
  # uses: aminya/setup-cpp@290824452986e378826155f3379d31bce8753d76
  uses: aminya/setup-cpp@v0.37.0
  with:
    # The compiler to use and its optional version separated by - e.g. llvm-13.0.0
    compiler: # optional
    # The CPU architecture
    architecture: # optional
    # The llvm version to install
    llvm: # optional
    # The gcc version to install
    gcc: # optional
    # The msvc version to install
    msvc: # optional
    # If should run vcvarsall?
    vcvarsall: # optional
    # The cmake version to install.
    cmake: # optional
    # The ninja version to install.
    ninja: # optional
    # The conan version to install.
    conan: # optional
    # The make version to install.
    make: # optional
    # The task version to install.
    task: # optional
    # The vcpkg version to install.
    vcpkg: # optional
    # The meson version to install.
    meson: # optional
    # The gcovr version to install.
    gcovr: # optional
    # The python version to install.
    python: # optional
    # The ccache version to install.
    ccache: # optional
    # The sccache version to install.
    sccache: # optional
    # The doxygen version to install.
    doxygen: # optional
    # The graphviz version to install.
    graphviz: # optional
    # The cppcheck version to install.
    cppcheck: # optional
    # The clang-tidy version to install.
    clangtidy: # optional
    # The clang-format version to install.
    clangformat: # optional
    # The opencppcoverage version to install.
    opencppcoverage: # optional
    # The kcov version to install.
    kcov: # optional
    # The 7z version to install.
    sevenzip: # optional
    # The nala version to install ("" or "legacy").
    nala: # optional
    # The powershell version to install.
    powershell: # optional
    # The timeout for installation of one tool (in minutes).
    timeout: # optional, default is 20



            - name: Cache
  uses: actions/cache@v4.0.2
  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
    restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    enableCrossOsArchive: # optional, default is false
    # Fail the workflow if cache entry is not found
    fail-on-cache-miss: # optional, default is false
    # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    lookup-only: # optional, default is false
    # Run the post step to save the cache even if another step before fails
    save-always: # optional, default is false
          
          
